name: Manual StormDNS Install
on: [workflow_dispatch]

jobs:
  manual-install:
    runs-on: ubuntu-latest
    steps:
      - name: Open Terminal (tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          # این گزینه کلید SSH را اجباری نمی‌کند و لینک وب می‌دهد
          limit-access-to-actor: false
