name: StormDNS Test
on: [workflow_dispatch] 

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Run StormDNS
        run: |
          # ۱. دانلود فایل اسکریپت
          curl -Ls https://raw.githubusercontent.com/nullroute1970/StormDNS/main/server_linux_install.sh -o install.sh
          # ۲. دادن دسترسی اجرا
          chmod +x install.sh
          # ۳. اجرای فایل دانلود شده با دسترسی روت
          sudo ./install.sh
          
      - name: Start Pinggy Tunnel
        run: |
          # اجرای تانل (پورت 8080)
          ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:8080 ssh.pinggy.io > pinggy_url.txt 2>&1 &
          sleep 5
          cat pinggy_url.txt

      - name: Keep Alive (Tmate)
        uses: mxschmitt/action-tmate@v3
